spring:
  application:
    name: off
springdoc:
  api-docs:
    version: openapi_3_0  # 3.1.0 대신 3.0.x 계열을 사용하도록 강제함
gemini:
  api-key: ${GEMINI_API_KEY}
  url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"