spring:
  application:
    name: off
  jpa:
    defer-datasource-initialization: true
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
springdoc:
  api-docs:
    version: openapi_3_0  # 3.1.0 대신 3.0.x 계열을 사용하도록 강제함
gemini:
  api-key: ${GEMINI_API_KEY}
  url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
jwt:
    secret: ${JWT_SECRET}
    expire-ms: 3600000

payment:
  client:
    key: ${PAYMENT_CLIENT_KEY}
  secret:
    key: ${PAYMENT_SECRET_KEY}